# Generated by Django 2.2.6 on 2019-11-13 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeHasTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.Barcode')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barcodes', models.ManyToManyField(through='codes.BarcodeHasTag', to='codes.Barcode')),
            ],
        ),
        migrations.AddField(
            model_name='barcodehastag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.Tag'),
        ),
        migrations.AddField(
            model_name='barcode',
            name='tags',
            field=models.ManyToManyField(through='codes.BarcodeHasTag', to='codes.Tag'),
        ),
    ]
